.PHONY: clean All

All:
	@echo "----------Building project:[ enum - Debug ]----------"
	@cd "enum" && "$(MAKE)" -f  "enum.mk"
clean:
	@echo "----------Cleaning project:[ enum - Debug ]----------"
	@cd "enum" && "$(MAKE)" -f  "enum.mk" clean
