.PHONY: clean All

All:
	@echo "----------Building project:[ ternaryOperator - Debug ]----------"
	@cd "ternaryOperator" && "$(MAKE)" -f  "ternaryOperator.mk"
clean:
	@echo "----------Cleaning project:[ ternaryOperator - Debug ]----------"
	@cd "ternaryOperator" && "$(MAKE)" -f  "ternaryOperator.mk" clean
